export const MOVIES_DATA_GATHERING_START = 'MOVIES_DATA_GATHERING_START';
export const MOVIES_DATA_GATHERING_SUCCESS = 'MOVIES_DATA_GATHERING_SUCCESS';
export const MOVIES_BOOKMARKS_DATA_GATHERING_SUCCESS = 'MOVIES_BOOKMARKS_DATA_GATHERING_SUCCESS';
export const TAGS_DATA_GATHERING_SUCCESS = 'TAGS_DATA_GATHERING_SUCCESS';
